sudo: required
services:
  - docker

before_install:
  - docker build -t dockersunil/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dockersunil/react-test npm test -- --coverage

after_success:
  - docker build -t dockersunil/multi-client ./client
  - docker build -t dockersunil/multi-nginx ./nginx
  - docker build -t dockersunil/multi-server ./server
  - docker build -t dockersunil/multi-worker ./worker

  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push dockersunil/dockersunil:multi-client
  - docker push dockersunil/dockersunil:multi-nginx
  - docker push dockersunil/dockersunil:multi-server
  - docker push dockersunil/dockersunil:multi-worker